replicaCount: 2

namespace: production

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

container:
  port: 80
  livenessProbe:
    httpGet:
      path: /health
      port: http
  readinessProbe:
    httpGet:
      path: /health
      port: http
  env:
    - name: NODE_ENV
      value: production

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  enabled: true
  type: ClusterIP
  port: 80

istio:
  enabled: false
  sidecar: true
  virtualService:
    gateways:
      - "https-pluang"
    hosts:
      - ""

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Frame-Options "SAMEORIGIN";
      add_header X-Content-Type-Options "nosniff";
      add_header X-XSS-Protection "1; mode=block";
      add_header Content-Security-Policy "frame-ancestors none";
      add_header Strict-Transport-Security "max-age=31536000;";
      server_tokens off;
      more_clear_headers Server;
  hosts:
    - host: merchant.pluang.com
      paths: [/]

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 500m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  metrics:
    cpu:
      targetAverageUtilization: 50
    memory:
      targetAverageUtilization: 50

tolerations: []

affinity: {}
